name: CI

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
        - os: windows-latest
          runtime: win-x64
        - os: ubuntu-latest
          runtime: linux-x64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow origin HEAD

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202

    - name: Clean
      run: dotnet nuget locals all --clear

    - name: Build
      run: dotnet build src --configuration Release

    - name: Test
      run: dotnet test src --configuration Release --collect:"XPlat Code Coverage"

    - name: Upload coverage
      uses: codecov/codecov-action@v1

    - name: Pack
      run: dotnet pack src --configuration Release --output build/artifacts/${{ matrix.runtime }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.runtime }}
        path: build/artifacts/${{ matrix.runtime }}

  publish:
    needs: build

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
    - name: Download Artifacts linux-x64
      uses: actions/download-artifact@v1
      with:
        name: linux-x64

    - name: Upload NuGet packages
      run: |
           for f in ./linux-x64/*.nupkg
           do
             curl -vX PUT -u "feliwir:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/feliwir/
           done
      shell: bash